### ISSUE TITLE
MD containing only code block causes an exception

### ISSUE THREAD

**Issue by genmeblog** [lread/test-doc-blocks#25]
Hi! I'm trying your library (yay, looks great) and faced some issue.

Having the following content of the `core.md` file:

````md
```clojure
(+ 1 2)
;; => 3
```
````

The following exception is thrown.

> Execution error (NullPointerException) at lread.test-doc-blocks/indent (test_doc_blocks.clj:29).
> Cannot invoke "Object.toString()" because "s" is null

The problem disappears when header is added, like:

````md
# anything

```clojure
(+ 1 2)
;; => 3
```
````

**Comment by lread** [comment]
Ah! Thanks, @genmeblog! Test-doc-blocks uses markdown headings to provide extra context in tests. I must not have tested a header-less scenario.

I'll take a peek sometime soon.
