### ISSUE TITLE
Enhance leiningen support

### ISSUE THREAD

**Issue by MIJOTHY** [lread/test-doc-blocks#8]
The current tool entrypoint ([`lread.test-doc-blocks/gen-tests`](https://github.com/lread/test-doc-blocks/blob/main/src/lread/test_doc_blocks.clj#L83)) expects a map to be supplied. While the clojure CLI does the transformation from [cli args into a map](https://clojure.org/reference/deps_and_cli#_execute_a_function) for the user when calling `-X`, other tools don't. For example, 

```sh
lein run -m lread.test-doc-blocks/gen-tests :docs '["*.md"]'
# Syntax error (ArityException) ...
# Wrong number of args (2) passed to: lread.test-doc-blocks/gen-tests

lein  run -m "lread.test-doc-blocks/gen-tests" '{:docs ["*.md"]}'
# Syntax error (ClassCastException) ...
# java.lang.Character cannot be cast to java.util.Map$Entry
```

This can be worked around by supplying a dedicated entrypoint namespace for your project, or by using a tool like `lein-exec` and calling
```sh
lein exec -ep \
     "(require '[lread.test-doc-blocks]) \
      (lread.test-doc-blocks/gen-tests {:docs [\"doc/*.md\"], :platform :clj})"
```

I can see two low-hanging fruits here for leiningen users:
1. Add a `-main` function that does the relevant consolidation of cli args into a map (in the same vein as the clojure CLI)
2. Add some docs for how to set the tool up with `lein`.

If this sounds good I can look at making a PR.

**Comment by lread** [comment]
Thanks for raising this @MIJOTHY! 

I think a `-main` entry point might also be helpful to:
- Windows users who can, for good reason, find Clojure CLI shell escaping very challenging in cmd and powershell shells
- Users who find -X escaping rules a bit esoteric and prefer a conventional command line. (Ex. in -X syntax, `'"strings must be quoted like so"'`).

I'm happy to take this one on myself but I will need your help though with docs on how to setup for lein usage.
Are there any special considerations when designing a `-main` lein-friendly command line?

Would something like these options work for lein?
```
-d, --doc=<file>...       Generate tests for code blocks found in file, repeat for multiple files (default: README.md)
-t, --target-root=<dir>   Target directory where tests are generated [default: ./target]
-p, --platform=<platform> By default, generate files for one of clj, cljs, or cljc [default: cljc] 
    --help                Show this help
```

An example usage (from this project's root) might be:
```
clojure -M -m lread.test-doc-blocks --doc README.md --doc doc/example.md \
  --target-root ./some-other/dir" --platform cljc
```

**Comment by MIJOTHY-V2** [comment]
Those options and the example look good to me. In terms of setting the tool up for `lein` in a `project.clj`, something like the following entries should work

```
{ ; ...
 :profiles
 {:gen-doc-tests
  {:test-paths ["target/test-doc-blocks/test"] 
   :dependencies [[com.github.lread/test-doc-blocks "1.0.146-alpha"]]}}
 :aliases
 {"run-doc-tests"
  ["with-profile" "gen-doc-tests" "do"
   ["run" "-m" "lread.test-doc-blocks"
    "--doc" "src/**.clj" "--doc" "doc/example.md"
    "--platform" "clj"]
   ["test"]]}}
```

**Comment by MIJOTHY** [comment]
Those options and the example look good to me. In terms of setting the tool up for `lein` in a `project.clj`, something like the following entries should work

```
{ ; ...
 :profiles
 {:gen-doc-tests
  {:test-paths ["target/test-doc-blocks/test"] 
   :dependencies [[com.github.lread/test-doc-blocks "1.0.146-alpha"]]}}
 :aliases
 {"run-doc-tests"
  ["with-profile" "gen-doc-tests" "do"
   ["run" "-m" "lread.test-doc-blocks"
    "--doc" "src/**.clj" "--doc" "doc/example.md"
    "--platform" "clj"]
   ["test"]]}}
```

**Comment by lread** [comment]
Thanks @MIJOTHY, that is very helpful!

**Comment by lread** [comment]
Small update. For future extensibility, I'll add cmd `gen-tests`.
For usability, I'll turf `--doc` and instead allow for a list of files.

```
clojure -M -m lread.test-doc-blocks gen-tests \
  --target-root ./some-other/dir" --platform cljc \
  README.md doc/example.md
```
